# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.IntegerField(default=0)),
                ('emp_name', models.CharField(max_length=200)),
                ('basic_pay', models.IntegerField(default=0)),
                ('division', models.CharField(max_length=200)),
                ('headq', models.CharField(default='Varanasi', max_length=50)),
                ('branch', models.CharField(max_length=200)),
            ],
        ),
    ]
