# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ta',
            field=models.IntegerField(default=500),
        ),
    ]
